export default {
    "":[],

    Choose:[],

    Kunnamkulam:[],

  Kodungallur: [
    "Edathiruthi, Chenthrappinni",
    "Kaipamangalam",
    "Perinjanam",
    "Pappinivattom",
    "Koolimuttam",
    "Ala,Panangad,Padinjare Vemballur",
    "Edavilangu",
    "Azhikkod",
    "Eriyad",
    "Vadama, Vadakkumbagam",
    "Kuruvilassery",
    "Avanur",
    "Kallur Thekkumuri",
    "Alathur",
    "Thirumukkulam",
    "Kakkulissery",
    "Poyya,Madathumpadi,Pallippuram",
    "Methala",
    "Lokamaleswaram, Pullut",
    "Vallivattom",
    "Thekkumkara",
    "Karumathra",
    "Wadakkumkara",
    "Puthenchira",
  ],
  Mukundapuram: [
    "Porathissery",
    "Madayikkonam",
    "Irinjalakuda",
    "Ananthapuram",
    "Muriyad",
    "Pullur",
    "Kallettumkara",
    "Thazhekkad",
    "Aloor",
    "Velookara",
    "Kaduppassery",
    "Kottanellur",
    "Manavalassery",
    "Karalam",
    "Edathirinji",
    "Poomangalam",
    "Padiyoor",
    "Kattoor",
    "Varantharappilly",
    "Nandipulam",
    "Mattathoor",
    "Vellikulangara",
    "Chengaloor",
    "Thoravu",
    "Parappukkara",
    "Nellayi",
    "Vallachira",
    "Arattupuzha",
    "Kallur",
    "Amballur",
  ],

  Chalakkudy: [
    "Pariyaram",
    "Kodassery",
    "Kuttichira",
    "Meloor",
    "Kizhakkummury",
    "Padinjare Chalakudy",
    "Kizhakke Chalakkudy",
    "Kodakara",
  ],
  
   Thalappally: ['Thiruvilwamala' ,'Kaniyarkode','Vadakkethara','Pazhayannur',
                'Elanad','Mullurkkara','Arangottukkara','Varavoor','Desamangalam','Arangottukara',
                'Cheruthuruthy','Panjal','Venganellur','Chelakkara','Kurumala','Venganellur',
                'Kondazhy','Chelakkode','Nelluvai','Kottappuram' ,'Kumaranellur','Velur','Vellattanjur',
                'Kadangode','Eyyal','Chowannur','Kanippayoor','Kunnamkulam','Arthat','Anjur','Kannippayoor',
                'Chowannur','Porkulam','Kattakampal','Kadavallur'],  

 

  Chavakkad: ['Punnayoorkulam', 'Vadakkekkad',
            'Pookkodu', 'Guruvayur', 'Thaikkad', 'Orumanayoor', 'Engandiyoor', 'Kadappuram', 'Manathala',
            'Punnayoor'],

  Thrissur:['Choondal', 'Kandanasseri', 'Elavally', 'Mullassery', 'Parakkad – Eravu Manakkodi – Veluthur',
            'Manalur / Karamukku', 'Vatanapilly', 'Venkitangu', 'Pavaratty', 'Thaikkad','Wadakkanchery', 'Kumaranellur',
            'Enkakkad', 'Thekkumkara', 'Enkakkad', 'Killannur', 'Kolazhy', 'Kuttur', 'Adat', 'Peramangalam',
            'Chittilappilly', 'Puzhakkal', 'Edakkalathur', 'Tholur', 'Mundoor', 'Peramangalam', 'Chittilappilly',
            'Mundoor', 'Avanoor', 'Mundathicode', 'Perangandoor', 'Wadakkanchery','Pananchery', 'Peechi', 'Puthur-Mannamangalam',
            'Marathakkara', 'Nadathara Part-Kozhukkully', 'Mulayam – Kainoor', 'Madakkathara', 'Vellanikkara',
            'Ollukkara-Nettissery', 'Ollur', 'Edakkunny', 'Kanimangalam', 'Koorkkanchery', 'Chiyyaram','Peringavu',
            'Chembukkavu', 'Thrissur', 'Ayanthole', 'Aranattukara', 'Koorkkanchery', 'Chiyyaram', 'Ollur', 
            'Ollukkara-Nettisseri', 'Nadathara', 'Vilvattom', 'Viyyur','Avinissery-Pallissery', 'Cherpu, Urakam, Arattupuzha',
            'Pullu, Alappat, Chazhoor-Kurumpilavu', 'Kizhuppillikkara, Thanniam, Vadakkummuri, Kizhakkummuri', 
            'Valappad', 'Nattika', 'Thalikkulam', 'Padiyam, Anthikkad', 'Paralam, Avinissery']
}
