export default {
	Choose:[],
	"":[],
	Chalakudy : ['Aloor', 'Annallur', 'Athirapilly', 'E.Chalakudy', 'Kakkulissery', 'Kallettumkara', 'Kallurthekkumury', 'Kallurvadakkumurry', 'Kizhakkumury', 'Kodakara', 'Kodassery', 'Kuruvilassery', 'Kuttichira', 'Mattathur', 'Meloor', 'Mupliyam', 'Nadipulam', 'Pariyaram','Thazhakkad', 'Thirumukkulam', 'Vadama', 'Varantharapilly', 'Vellikulangara', 'W. Chalakudy'],
	Chavakkad : ['Elavally', 'Engandiyoor', 'Guruvayur', 'Kadappuram', 'Manathala', 'Mullassery', 'Nattika', 'Orumanayoor', 'Pavaraty', 'Pookode', 'Punnayoor', 'Punnayoorkulam', 'Thaikkad Part', 'Thalikulam', 'Vadakkekkad', 'Valappad', 'Vatanapally', 'Venkidagu'],
	Kodungallur : ['Aazhikode', 'Ala', 'Edathurithy', 'Edavilangu', 'Eriyad', 'Kaippamangalam', 'Koolimuttam', 'Lokamalleswaram', 'Methala', 'P.Vemballur', 'Pappinivattom', 'Perinjanam', 'Poyya', 'Pullut'],
	Kunnamkulam : ['Aloor', 'Anjur', 'Arthat', 'Chemanthatta', 'Choondal', 'Chowannur', 'Eranellur', 'Eyyal', 'Kadangoe', 'Kadavallur', 'Kandanissery', 'Kanippayur Village Part', 'Kattakambal', 'Kottapuram', 'Kumaranellur', 'Kunnamkulam', 'Nelluvai', 'Porkulam', 'Vellattanjur'],
	Mukunthapuram : ['Amballur', 'Ananthapuram', 'Chengalur', 'Edathirinji', 'Irinjalakuda', 'Kaduppassery', 'Karalam Part', 'Karumathra', 'Kattoor', 'Kottanellur', 'Madayikonam', 'Manavalassery Part', 'Muriyad', 'Nellai', 'Nenmanikkara', 'Padiyoor', 'Parappukara', 'Poomangalam', 'Porathissery', 'Pullur', 'Puthenchira', 'Thekkumkara', 'Thoravu', 'Thottipal', 'Thrikkur', 'Vadakkumkara', 'Vallivattom', 'Velukara'],
	Thalapilly : ['Arankottukara', 'Attoor', 'Chelakara', 'Chelakode', 'Cheruthuruthy', 'Deshamangalam', 'Elanad', 'Enkakkad', 'Kondazhi', 'Kumaranellur', 'Kurumala', 'Pambady', 'Panjhal', 'Pazhayannur', 'Peringadoor', 'Puthuruthy', 'Thekkumkara', 'Thiruvillamala', 'Vadakkethara', 'Varavoor', 'Venganellur', 'Wadakkancherry'],
	Thrissur : ['Adat', 'Alappad', 'Anjur', 'Anthikkad', 'Aranattukara', 'Arattupuzha', 'Avanoor', 'Avinissery ', 'Ayyanthole', 'Chazhur', 'Chembukkavu', 'Cherpu', 'Chevoor','Chilliapilly', 'Chiyyaram Part', 'Choolissery', 'Edakalathur', 'Edakunni', 'Injamudi', 'Kainoor', 'Kanimangalam', 'Karamukku', 'Killannur', 'Kizhpullikara', 'Kolazhi', 'Koorkkenchery Part', 'Kozhukully', 'Kurichikara', 'Kurimbilavu', 'Kuttur', 'Madakkathara', 'Manakodi', 'Manaloor', 'Manamangalam', 'Marathakara', 'Mulayam', 'Nadathara', 'Ollukara', 'Ollur Part', 'Padiyam', 'Pananchery', 'Parakkad', 'Paralam', 'Peechi', 'Peramangalam', 'Peringavu', 'Pullu', 'Puthur', 'Puzhakkal', 'Thangalur', 'Thannyam', 'Tholur', 'Thrissur', 'Vadakkumury', 'Vallachira', 'Vellanikara', 'Venginissery', 'Vilvattom', 'Viyyur']
}
